Task1/Models/Data.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Task1.Models
{
    public class Data
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)] //設定流水編號
        public int Id { get; set; }

        [StringLength(50), Required]   //Required 該欄位非null值
        public string Context { get; set; }
    }
}

Task1/Models/DataDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task1.Models
{
    public class DataDTO
    {
       public string AccessType { get; set; }

       public int Id { get; set; }

       public string Context { get; set; }
    }
}

Task1/Models/DataService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task1.Models
{
    public class DataService
    {
    }
}

Task1/Models/DataVM.cs
namespace Task1.Models
{
    public class DataVM
    {
        public int Id { get; set; }

        public string Context { get; set; }
    }
}

Task1/Models/MbrContext.cs
using System.Data.Entity;

namespace Task1.Models
{
    public class MbrContext : DbContext
    {
        public DbSet<Data> Data { get; set; }

        public MbrContext() : base("name=DbConnection")
        {
        }
        
    }
}

Task1/Controllers/DataController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Task1.Models;

namespace Task1.Controllers
{
    public class DataController : Controller
    {
        private MbrContext MbrContext = new MbrContext();

        /// <summary>
        /// 查詢頁面
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var vm = new List<DataVM>();
            var datas = MbrContext.Data.ToList();  //後端連到資料庫，取得資料

            foreach (var data in datas)            //將資料打包成物件
            {
                vm.Add(new DataVM()
                {
                    Id = data.Id,
                    Context = data.Context
                });
            }
            return View(vm);                      //將物件回傳至前端
        }

        /// <summary>
        /// 新增頁面
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// 編輯頁面
        /// </summary>
        public ActionResult Edit(int id)          //撈取單一筆資料
        {
            var data = MbrContext.Data.FirstOrDefault(x => x.Id == id);
            var vm = new DataVM()                //進入該Action，做宣告
            {
                Id = data.Id,
                Context = data.Context
            };
            return View(vm);
        }
        /// <summary>
        /// 存取資料
        /// </summary>
        public ActionResult Access(DataDTO dto)
        {
            Data entity = null;
            switch (dto.AccessType)
            {
                case "Create":
                    MbrContext.Data.Add(new Data { Context = dto.Context });
                    break;

                case "Update":
                    entity = MbrContext.Data.FirstOrDefault(x => x.Id == dto.Id);
                    entity.Context = dto.Context;  //存取動作
                    break;

                case "Delete":
                    entity = MbrContext.Data.FirstOrDefault(x => x.Id == dto.Id);
                    MbrContext.Data.Remove(entity); //刪除資料
                    break;
            }
            MbrContext.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Task1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Task1/Views/Data/Create.cshtml
<h2>新增頁面</h2>

@using (Html.BeginForm("Access", "Data", new { AccessType = "Create" }, FormMethod.Post))
{
    <div class="form-group">
        <div class="form-group">
            <label>名字</label>
            <input for="name" class="form-control" id="Context" name="Context">
        </div>
        <button type="submit" class="btn btn-primary">確定</button>
        <a class="btn btn-info" href="@Url.Action("Index", "Data")">取消</a>
    </div>
}

Task1/Views/Data/Edit.cshtml
@model Task1.Models.DataVM

<h2>編輯頁面</h2>

@using (Html.BeginForm("Access", "Data", new { AccessType = "Update", Id = Model.Id }, FormMethod.Post))
{
    <div class="form-group">
        <div class="form-group">
            <label>名字</label>
            <input class="form-control" id="Context" name="Context" value="@Model.Context">
        </div>
        <button type="submit" class="btn btn-primary">確定</button>
        <a class="btn btn-success" href="@Url.Action("Index", "Data")">取消</a>
    </div>
}

Task1/Views/Data/Index.cshtml
@model List<Task1.Models.DataVM>
<style>
    th, td {
        text-align: center /*置中， text-align:left; //向左對齊*/
    }
</style>

<h2>查詢頁面</h2>
<br />
<a class="btn btn-warning" style="margin-bottom:10px" href="@Url.Action("Create", "Data")">新增</a>
<table class="table">
    <thead>
        <tr class="info">
            <th scope="col">id</th>
            <th scope="col">name</th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model.Count > 0)
            {
                foreach (var data in Model)
                {
                    <tr style="     background-color:#E8FFFF">
                        <td>@data.Id</td>
                        <td>@data.Context</td>
                        <td>
                            <a class="btn btn-primary" href="@Url.Action("Edit", "Data", new { Id = data.Id })">編輯</a>
                            <a class="btn btn-info" onclick="Delete(@data.Id)">刪除</a>
                        </td>
                    </tr>
                }
            }
        }
    </tbody>
</table>
<script>
               function Delete(Id) {
                    if (confirm(確定刪除)) {
                        $.ajax({
                            type: 'POST',
                            url: "@Url.Action("Access","Data")",
                            data: {
                                AccessType: "Delete",
                                Id: Id,
                            },
                            success: function () {
                                location.reload();
                            }
                        });
                    }
                }
</script>

Task1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Task1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Task1/Views/Home/Index.cshtml
<div class="text-center" style="margin-top:5%;">
    <h1 style="font-size:80px;">Website </h1>
    <a href="#">
        <img src="~/Images/HomePage/p1.png" style="display:block; width: 100%;  margin:auto;" />
    </a>
</div>

Task1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Website</title>
    <link rel="icon" href="@Url.Content("~/Images/favicon.ico")">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-headedkr">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Athena", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("查詢", "Index", "Data")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <div id="preloader"></div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>